// Generated by CoffeeScript 1.10.0
(function() {
  var CartsModel, CartsService;

  CartsModel = require('../model/carts_model');

  CartsService = {
    addCarts: function(params, cbf) {
      var cart, query;
      cart = new CartsModel(params);
      query = {
        _id: params._id
      };
      return CartsModel.findOne(query, function(err, doc) {
        if (err) {
          return cbf(err, null);
        } else {
          if (doc && doc.length > 0) {
            return CartsModel.findOneAndUpdate(query, {
              $set: params
            }, function(err, doc) {
              if (err) {
                return cbf(err, null);
              } else {
                return cbf(null, doc);
              }
            });
          } else {
            return cart.save(function(err, doc) {
              if (err) {
                return cbf(err, null);
              } else {
                return cbf(null, doc);
              }
            });
          }
        }
      });
    },
    findCarts: function(params, cbf) {
      return CartsModel.find(params, function(err, docs) {
        if (err) {
          return cbf(err, null);
        } else {
          return cbf(null, docs);
        }
      });
    },
    deleteCarts: function(params, cbf) {
      return CartsModel.remove(params, function(err, doc) {
        if (err) {
          return cbf(err, null);
        } else {
          return cbf(null, doc);
        }
      });
    }
  };

  module.exports = CartsService;

}).call(this);
