// Generated by CoffeeScript 1.10.0
(function() {
  var UserModel, UserService;

  UserModel = require('../model/user_model');

  UserService = {
    addUser: function(params, cbf) {
      var query, user;
      user = new UserModel(params);
      query = {
        _id: params._id
      };
      return UserModel.findOne(query, function(err, doc) {
        if (err) {
          return cbf(err, null);
        } else {
          if (doc && doc.length > 0) {
            return UserModel.findOneAndUpdate(query, {
              $set: params
            }, function(err, doc) {
              if (err) {
                return cbf(err, null);
              } else {
                return cbf(null, doc);
              }
            });
          } else {
            return user.save(function(err, doc) {
              if (err) {
                return cbf(err, null);
              } else {
                return cbf(null, doc);
              }
            });
          }
        }
      });
    },
    findOneUser: function(params, cbf) {
      console.log('params: ', params);
      return UserModel.findOne(params, function(err, doc) {
        if (err) {
          return cbf(err, null);
        } else {
          console.log("doc:", doc);
          return cbf(null, doc);
        }
      });
    },
    findAllUser: function(params, cbf) {
      return UserModel.find(params, function(err, docs) {
        if (err) {
          return cbf(err, null);
        } else {
          return cbf(null, docs);
        }
      });
    },
    deleteUser: function(params, cbf) {
      return UserModel.remove(params, function(err, doc) {
        if (err) {
          return cbf(err, null);
        } else {
          return cbf(null, doc);
        }
      });
    }
  };

  module.exports = UserService;

}).call(this);
