// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require("express");

  router = express.Router();

  router.get("/", function(req, res, next) {
    return res.render("index", {
      "title": "coffee-script"
    });
  });

  router.get("/test", function(req, res, next) {
    return res.render("index", {
      "title": "node-dev add succ!"
    });
  });

  router.get("/new", function(req, res, next) {
    return res.render("index", {
      "title": "new"
    });
  });

  router.get("/ssh", function(req, res, next) {
    return res.render("index", {
      "title": "ssh"
    });
  });

  module.exports = router;

}).call(this);
