// Generated by CoffeeScript 1.10.0
(function() {
  var router;

  router = function(app) {
    app.get("/", function(req, res, next) {
      return res.render("index", {
        "title": "coffee-script"
      });
    });
    app.get("/test", function(req, res, next) {
      return res.render("index", {
        "title": "node-dev add succ!"
      });
    });
    app.get("/new", function(req, res, next) {
      return res.render("index", {
        "title": "new"
      });
    });
    return app.get("/ssh", function(req, res, next) {
      return res.render("index", {
        "title": "ssh"
      });
    });
  };

  module.exports = router;

}).call(this);
