// Generated by CoffeeScript 1.10.0
(function() {
  var CartsService;

  CartsService = require('../service/carts_service');

  module.exports.save = function(req, res, cbf) {
    var params, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref17, ref18, ref19, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9;
    params = {};
    params.uId = ((ref = req.body) != null ? ref.uId : void 0) || ((ref1 = req.params) != null ? ref1.uId : void 0) || ((ref2 = req.query) != null ? ref2.uId : void 0) || '';
    params.cId = ((ref3 = req.body) != null ? ref3.cId : void 0) || ((ref4 = req.params) != null ? ref4.cId : void 0) || (typeof req.query === "function" ? req.query(cId || '') : void 0);
    params.cName = ((ref5 = req.body) != null ? ref5.cName : void 0) || ((ref6 = req.params) != null ? ref6.cName : void 0) || ((ref7 = req.query) != null ? ref7.cName : void 0) || '';
    params.cPrice = ((ref8 = req.body) != null ? ref8.cPrice : void 0) || ((ref9 = req.params) != null ? ref9.cPrice : void 0) || ((ref10 = req.query) != null ? ref10.cPrice : void 0) || '';
    params.cImgId = ((ref11 = req.body) != null ? ref11.cImgId : void 0) || ((ref12 = req.params) != null ? ref12.cImgId : void 0) || ((ref13 = req.query) != null ? ref13.cImgId : void 0) || '';
    params.cQuantity = ((ref14 = req.body) != null ? ref14.cQuantity : void 0) || ((ref15 = req.params) != null ? ref15.cQuantity : void 0) || ((ref16 = req.query) != null ? ref16.cQuantity : void 0) || '';
    params.cStatus = ((ref17 = req.body) != null ? ref17.cStatus : void 0) || ((ref18 = req.params) != null ? ref18.cStatus : void 0) || ((ref19 = req.query) != null ? ref19.cStatus : void 0) || '';
    return CartsService.addCarts(params, cbf);
  };

  module.exports.find = function(req, res, cbf) {
    var params;
    params = {};
    return CartsService.findCarts(params, cbf);
  };

  module.exports.remove = function(req, res, cbf) {
    var params, ref, ref1, ref2;
    params = {};
    params._id = ((ref = req.body) != null ? ref._id : void 0) || ((ref1 = req.query) != null ? ref1._id : void 0) || ((ref2 = req.params) != null ? ref2._id : void 0);
    return CartsService.deleteCarts(params, cbf);
  };

}).call(this);
