// Generated by CoffeeScript 1.10.0
(function() {
  var CommodityService;

  CommodityService = require('../service/commodity_service');

  module.exports.save = function(req, res, cbf) {
    var params, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8;
    params = {};
    params.name = ((ref = req.body) != null ? ref.name : void 0) || ((ref1 = req.params) != null ? ref1.name : void 0) || ((ref2 = req.body) != null ? ref2.name : void 0);
    params.price = ((ref3 = req.body) != null ? ref3.price : void 0) || ((ref4 = req.params) != null ? ref4.price : void 0) || ((ref5 = req.body) != null ? ref5.price : void 0);
    params.imgSrc = ((ref6 = req.body) != null ? ref6.imgSrc : void 0) || ((ref7 = req.params) != null ? ref7.imgSrc : void 0) || ((ref8 = req.body) != null ? ref8.imgSrc : void 0);
    return CommodityService.addCommodity(params, cbf);
  };

  module.exports.find = function(req, res, cbf) {
    var params;
    params = {};
    return CommodityService.findCommodity(params, cbf);
  };

  module.exports.remove = function(req, res, cbf) {
    var params, ref, ref1, ref2;
    params = {};
    params._id = ((ref = req.body) != null ? ref._id : void 0) || ((ref1 = req.params) != null ? ref1._id : void 0) || ((ref2 = req.body) != null ? ref2._id : void 0);
    return CommodityService.deleteCommodity(params, cbf);
  };

}).call(this);
