// Generated by CoffeeScript 1.10.0
(function() {
  var UserService;

  UserService = require('../service/user_service');

  module.exports.find_user = function(req, res, cbf) {
    var params;
    params = {
      userid: '1'
    };
    return UserService.findUser(params, cbf);
  };

}).call(this);
