// Generated by CoffeeScript 1.10.0
(function() {
  var connection, mongoose;

  mongoose = require('mongoose');

  connection = mongoose.connect('mongodb://localhost:27017/weixin');

  module.exports.mongoose = mongoose;

}).call(this);
